<a href="https://colab.research.google.com/github/mahananda123/Data_Collection/blob/main/CaseStudy_of_Shopping_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Collect shopping data from sqlite
The attached shopping.sqlite file contains a dummy shopping dataset.

###Establish connection with data base

In [10]:
import sqlite3

In [11]:
connection=sqlite3.connect('/content/shopping.sqlite')
cursor=connection.cursor()

In [12]:
query='''
select name from sqlite_master
where type='table';
'''

In [13]:
cursor.execute(query)
results=cursor.fetchall()
results

[('customer_shopping_data',)]

In [19]:
#retrive information from data base
query='''
select * from customer_shopping_data
limit 3;
'''
cursor.execute(query)
result=cursor.fetchall()
result

[('I138884',
  'C241288',
  'Female',
  28,
  'Clothing',
  5,
  1500.4,
  'Credit Card',
  '5/8/2022',
  'Kanyon'),
 ('I317333',
  'C111565',
  'Male',
  21,
  'Shoes',
  3,
  1800.51,
  'Debit Card',
  '12/12/2021',
  'Forum Istanbul'),
 ('I127801',
  'C266599',
  'Male',
  20,
  'Clothing',
  1,
  300.08,
  'Cash',
  '9/11/2021',
  'Metrocity')]

Fetch all the records

In [34]:
query='''
select * from customer_shopping_data;
'''
cursor.execute(query)
resultx=cursor.fetchall()

In [35]:
import pandas as pd

In [36]:
df=pd.DataFrame(resultx)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16029 entries, 0 to 16028
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       16029 non-null  object
 1   1       16029 non-null  object
 2   2       16029 non-null  object
 3   3       16029 non-null  int64
 4   4       16029 non-null  object
 5   5       16029 non-null  int64
 6   6       16029 non-null  float64
 7   7       16029 non-null  object
 8   8       16029 non-null  object
 9   9       16029 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 1.2+ MB

In [37]:
df.iloc[0]

0        I138884
1        C241288
2         Female
3             28
4       Clothing
5              5
6         1500.4
7    Credit Card
8       5/8/2022
9         Kanyon
Name: 0, dtype: object

Set column names

In [38]:
df.columns=list(df.iloc[0])

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16029 entries, 0 to 16028
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   I138884      16029 non-null  object
 1   C241288      16029 non-null  object
 2   Female       16029 non-null  object
 3   28           16029 non-null  int64
 4   Clothing     16029 non-null  object
 5   5            16029 non-null  int64
 6   1500.4       16029 non-null  float64
 7   Credit Card  16029 non-null  object
 8   5/8/2022     16029 non-null  object
 9   Kanyon       16029 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 1.2+ MB

In [40]:
df.head()

,I138884,C241288,Female,28,Clothing,5,1500.4,Credit Card,5/8/2022,Kanyon
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon

In [41]:
df.tail()

,I138884,C241288,Female,28,Clothing,5,1500.4,Credit Card,5/8/2022,Kanyon
16024,I100795,C232822,Male,62,Books,2,30.30,Debit Card,6/7/2022,Kanyon
16025,I192426,C246689,Female,50,Clothing,2,600.16,Cash,23/07/2021,Kanyon
16026,I334213,C322370,Male,24,Toys,1,35.84,Credit Card,30/08/2021,Metrocity
16027,I273812,C773268,Female,67,Toys,1,35.84,Debit Card,14/07/2022,Mall of Istanbul
16028,I165772,C249257,Female,43,Clothing,3,900.24,Credit Card,4/7/2021,Forum Istanbul

In [42]:
df.to_csv('/content/shopping.csv')

In [43]:
cursor.close()
connection.close()